services:
  postgres:
    image: postgres:latest

    container_name: worklynx-postgres

    environment:
      POSTGRES_DB: worklynx
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
