server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
