spring:
  application:
    name: backend

  server:
    servlet:
      context-path: /api

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/worklynx
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-google-client-id
            client-secret: your-google-client-secret
